"""empty message

Revision ID: 2a4d42fbbee2
Revises: f6bd18470351
Create Date: 2018-01-22 16:39:06.242615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4d42fbbee2'
down_revision = 'f6bd18470351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postal_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=True),
    sa.Column('the_geom', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('paystats', 'postal_code_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paystats', sa.Column('postal_code_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('postal_codes')
    # ### end Alembic commands ###
