"""empty message

Revision ID: 9171fbaedea9
Revises: 2a4d42fbbee2
Create Date: 2018-01-22 17:26:27.027492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9171fbaedea9'
down_revision = '2a4d42fbbee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paystats', sa.Column('postal_code_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'paystats', 'postal_codes', ['postal_code_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paystats', type_='foreignkey')
    op.drop_column('paystats', 'postal_code_id')
    # ### end Alembic commands ###
