"""empty message

Revision ID: f6bd18470351
Revises: d0fe6d0df9c1
Create Date: 2018-01-22 09:01:01.677094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6bd18470351'
down_revision = 'd0fe6d0df9c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paystats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('p_month', sa.Date(), nullable=True),
    sa.Column('p_age', sa.String(), nullable=True),
    sa.Column('p_gender', sa.String(), nullable=True),
    sa.Column('postal_code_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pays')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pays',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=20, scale=10), autoincrement=False, nullable=True),
    sa.Column('p_month', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('p_age', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('p_gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pays_pkey')
    )
    op.drop_table('paystats')
    # ### end Alembic commands ###
